### ISSUE TITLE
如果一个测试集合有多个PLUGIN_ENV怎么设置呢？

### ISSUE THREAD

**Issue by liugddx** [lm93129/drone_yapi_test#1]

**Comment by lm93129** [comment]
这个我建议你可以配置多个CI任务，因为如果有多个PLUGIN_ENV就需要考虑你这个PLUGIN_ENV对应的是哪些PLUGIN_ID，还是说都要跑

**Comment by liugddx** [comment]
您好：
    你看我这种情况，但是yapi提供了一个服务地址直接调用即可，是否可以基于这个测试？
   



804167098@qq.com
 
发件人： 懒猫
发送时间： 2020-04-02 16:00
收件人： lm93129/drone_yapi_test
抄送： liugddx; Author
主题： Re: [lm93129/drone_yapi_test] 如果一个测试集合有多个PLUGIN_ENV怎么设置呢？ (#1)
这个我建议你可以配置多个CI任务，因为如果有多个PLUGIN_ENV就需要考虑你这个PLUGIN_ENV对应的是哪些PLUGIN_ID，还是说都要跑

**Comment by lm93129** [comment]
配置多个CI任务即可
