### ISSUE TITLE
Yapi请求错误: Get "https://yapi.com/api/open/run_auto_test?token=&&mode=json&email=false&download=false&descendants=&id=2693": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by hanguisheng** [lm93129/drone_yapi_test#3]
跑流水线触发问题：Yapi请求错误: Get "https://yapi.com/api/open/run_auto_test?token=&&mode=json&email=false&download=false&descendants=&id=2693": x509: certificate signed by unknown authority

**Comment by lm93129** [comment]
请使用自己的yapi地址，你自己的yapi地址应该不会是https://yapi.com/api/open/run_auto_test?

另外看报错，这应该是ssl证书错误导致的，如果使用https，则要求证书是正常的CA证书，不能是自己生成的证书。

**Comment by hanguisheng** [comment]
嗯嗯，Yapi 粘贴错误了，  我也是认为是证书问题，感谢
